### ISSUE TITLE
Dinasty ao

### ISSUE THREAD

**Issue by Askmewho** [guidota/ao-java#16]
hi, whats the actual state of this project?

**Comment by Derillo** [comment]
@Askmewho Hello! Are you cooper or locke? You are welcome here!
the project is in development, join the discord if you want to be up to date. see you soon! https://discord.gg/TfXMz2

**Comment by jopiortiz** [comment]
If hoy want to ser forma yourself how dar we've come. Just clone the repo, compile `desktop` and connect to the following server:

IP: 45.235.98.117
Port: 9000

**Comment by Askmewho** [comment]
@jopiortiz I will!
